### ISSUE TITLE
OpenMAX support included?

### ISSUE THREAD

**Issue by JakeSmarter** [multiwirth/adreno-3xx-developer-driver#2]

**Comment by multiwirth** [comment]
🤔
I guess you already found an answer?
If not, sadly i don´t know it for sure.
As written in docs, OpenMAX is a part of android and the hardware vendors only have to implement a small fraction of it to make use of OMX.
But i´ve seen seperate OMX labeled libs on some devices with qualcomm SoC so maybe you´ll need different drivers aswell.
Anyways these files provided here are "as is" from Qualcomm so i didn´t mess around with it at all.
Hope this helps in any way :)

**Comment by GITNE** [comment]
Thank you for answering my inquiry. I did not expect anyone to answer.

> I guess you already found an answer?
> As written in docs, OpenMAX is a part of android and the hardware vendors only have to implement a small fraction of it to make use of OMX.

Sort of; I have downloaded the repo and scanned the shared object files for OMX dynamic symbols, more specifically for [OpenMAX&#x00A0;DL](https://www.khronos.org/registry/OpenMAX-DL) symbols. OpenMAX&#x00A0;DL is that *small fraction* that hardware vendors have to implement in order to expose their hardware codecs to OpenMAX&#x00A0;AL.

As far as I can tell this driver seems to have support for Adreno’s hardware JPEG codec, which is part of the camera stack. :+1: However, I cannot find anything related to any video codec potentially available in the Adreno 3xx’s line of products, like h.264 or VP8. :disappointed: The `proprietary/etc/firmware/vidc_1080p.fw` firmware file seems to be the only hint at video acceleration. But, this is just me guessing.

So, my answer is basically: no, I did not find any satisfying answer. In an ideal world I would like to see an open source OpenMAX DL driver for Adreno’s video acceleration core. This would substantially extend the lifetime of billions of existing Adreno/Qualcomm/Exynos devices, especially in developing countries and secondhand markets. Unfortunately, this dream looks like an unlikely scenario, at least for the foreseeable future.:cry:

**Comment by multiwirth** [comment]
If this would be helpful in any way, i could try to collect and share the "stable" adreno drivers found on my HTC One M8 or Samsung Galaxy S3 Neo.
Both run on 3xx series.
If i recall correct, this dev drivers had issues on some devices.
Maybe it´s simply missing something.

**Comment by GITNE** [comment]
> If this would be helpful in any way, i could try to collect and share the "stable" adreno drivers found on my HTC One M8 or Samsung Galaxy S3 Neo.

Thank you for your efforts but I do not think they are going to work, so I will have to stay on software fallback for now.

> If i recall correct, this dev drivers had issues on some devices.
> Maybe it´s simply missing something.

Maybe, or maybe I am just doing something wrong.

> As far as I can tell this driver seems to have OMX support for Adreno’s hardware JPEG codec, which is part of the camera stack.

I have just realized that I was talking about a [different driver package](https://github.com/MSM8930-Samsung/proprietary_vendor_samsung_loganreltexx "MSM8930"). This developer driver package however seems to have no visible OMX support. Again, maybe I am doing something wrong. Besides, judging by the `a330_pfp.fw` and `a330_pm4.fw` files this driver is targeting the Adreno 330 series.

I was also thinking that since the Adreno and Radeon families of GPUs are related, maybe their video cores are too. Open source drivers do exist for AMD’s UVD. So, maybe there is a connection. Anyway, thank you for your effort. :+1:
